export const black = '\x1B[30m'
export const red = '\x1B[31m'
export const green = '\x1B[32m'
export const yellow = '\x1B[33m'
export const blue = '\x1B[34m'
export const magenta = '\x1B[35m'
export const cyan = '\x1B[36m'
export const white = '\x1B[37m'
export const reset = '\x1B[0m'
export const log = (color: string, log: string) => { console.log(color + log + reset) }